$env:FRIEND_SUPABASE_URL="https://daammggjutepyojdhtzy.supabase.co"
$env:FRIEND_SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhYW1tZ2dqdXRlcHlvamRodHp5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTg5ODg4MywiZXhwIjoyMDkxNDc0ODgzfQ.XQ2S7F3scF_k5AIpmUCbexXVP7HR0gMUiKTVpVwhGUc"
$env:SUPABASE_URL="https://kfsjwzsxlaabnixpgoke.supabase.co"
$env:SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmc2p3enN4bGFhYm5peHBnb2tlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTg4MjMxMCwiZXhwIjoyMDkxNDU4MzEwfQ.5_h2nzXvnrJzt8Pjv49JzHxGg6QLGTValvv4qVTUuV8"

node D:\ResQNet\scripts\sync-friend-data.js